### ISSUE TITLE
关于dacnn

### ISSUE THREAD

**Issue by xilinniao123** [zake7749/Closer#1]
您好：
 感谢分享！有两个问题需要请教下：
1、关于dacnn的堆叠方式：
“此外,这种堆叠形式的soft align也能考虑为跳跃 性的Self attention(每叠两次就会attend到自身)”
请问这里为啥两次堆叠就等价为一次 跳跃性self attention？
2、我看您的代码中在第一次做 soft alignment之前一般都只有 word embedding，而现在一般在第一次soft alignment之前都会做word embeddign＋cnn/rnn encoding,请问您这里为啥选择这种做法

**Comment by zake7749** [comment]
1. 這裡想表達的是假設句子 A, B soft alignment 後的結果為 A', B'，A' 會是 B 的 weighted sum，而 B' 會是 A 的 weighted sum。如果我們進一步對 A', B' 再做一次 soft alignment，得出的 A'' 會是 B' 的 weighted sum，可進一步以 A 的 weighted sum 表示。

2. 我用到的有 3 種模型， decomposable attention 本身不涉及任何序列建模。CPRNN 是遵循 CAFE 的思路 ( 用 RNN 來傳遞在 word level 匹配後的結果 )，所以採用 word level 的 soft alignment。而 DACNN 使用的是多層次 ( word level + context level ) 的 soft alignment，具體來說，它包含了 word level 的、word level + 單層 CNN 的、......、word level + n 層 CNN 的 soft aligment。
